name: Arduino Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Arduino Lint
        uses: arduino/arduino-lint-action@v2.0.0
        with:
          project-type: library
          compliance: strict

